### ISSUE TITLE
Component: Dashboard Settings

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#114]
The latest [sketch design](https://sketch.cloud/s/rQMvE/all/prototype/dashboard/play) has detailed the new "Screen Settings" interactions in further detail:

<img width="1008" alt="dashboardsettingsfooter" src="https://user-images.githubusercontent.com/22080/41384584-87daaad2-6f2b-11e8-8baf-f97c549cd053.png">

The Screen Settings button appears in the footer area below the dashboard blocks. When the button is clicked, an Ellipsis menu is shown that allows users to toggle the blocks shown on their dashboard:

<img width="1086" alt="dashboardsettingsmenuopen" src="https://user-images.githubusercontent.com/22080/41384602-a7ffb85c-6f2b-11e8-8299-b33ea2ea7fbc.png">

For this enhancement - the following items are needed:

- A new component for the footer area of the Dashboard
- A component for Screen Settings, that when clicked exposes an Ellipsis menu

Eventually the selections in this menu will need to be persisted in some manner. In our hangout this week I brought up the notion of storing the selections as user options as they will need to be persisted between browsers/sessions. But we can tackle that in a future PR.

**Comment by justinshreve** [comment]
I started working on this, but I have a design related issue with the popover.

As different blocks/overviews are toggled, the "screen settings" jumps around the screen (since the height of the content changes). The bubble however, doesn't update it's position and there doesn't seem to be an easy way to force it to update right now. It seems to update if the page scrolls, but it seems hacky to scroll around the page as you update widgets. I've attached a little video showing what I mean: https://cloudup.com/cgI8WyVlREN

Does anyone have any ideas here? Could we fix the position of this somewhere? Maybe the upper right corner where the classic wp-admin screen option button is? Or maybe the lower right hand corner? 

cc @woocommerce/woo-core-design

**Comment by LevinMedia** [comment]
Heya Justin - Can we try floating it right, opposite the date range picker?

<img width="1454" alt="screen shot 2018-08-06 at 8 25 39 am" src="https://user-images.githubusercontent.com/4500952/43725933-b0f6c8dc-9952-11e8-8499-3432132efc52.png">

It could wrap under the date range picker at 782 or less.  

If we have to contend with the other screen settings tabs (I don't see them in your video) we should probably re-name the button we're looking at "Dashboard Settings" to disambiguate it from the others.

**Comment by justinshreve** [comment]
@timmyc Per the design changes in p6riRB-3qG-p2, I think we should close this one out and create a few issues to implement the new behavior. There is more going on now then just show/hide. For example blocks can be reordered, we can have multiple instances of blocks, etc.
