### ISSUE TITLE
Chart: Update X-Axis Logic for Single Date

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1156]
1. Single days and hourly intervals: When the selected date range is a single day, (ie: a single day picked from the custom date range picker, "today", or "yesterday" in the presets) the default interval should be "Hours"
2. When viewing an entire day with hourly intervals, the x-axis ticks should start at 12am and end at 11pm. 
3. When the time frame is today's date, and set to hourly intervals, the graph only plots up to and including the current hour of the day. 
4. When viewing single day time frames the secondary X axis should always include the month, day and year. 

<img width="975" alt="screen shot 2018-12-14 at 10 05 45 pm" src="https://user-images.githubusercontent.com/4500952/50039772-ac20de00-ffec-11e8-88c6-03971b28fe09.png">

**Comment by Aljullu** [comment]
I created #1195 which fixes 1, 2 and 4. But regarding this one:

> When the time frame is today's date, and set to hourly intervals, the graph only plots up to and including the current hour of the day.

My opinion is that this should be implemented in the API. I think the client component must be 'dumb' and print all data it receives, without checking if it's in the past or future.

Adding a limitation to only display past data would not allow us or other developers to create charts with future data like an _Expected revenue_ chart, for example, which would be a legit chart to implement for an extension.

Thoughts @timmyc?

**Comment by timmyc** [comment]
Excellent point @Aljullu - I think that is the same bug reported in #957 - just a different interval, but should be the same regardless - the API should zero fill in all intervals on both ends of a date range when there is no data.

**Comment by Aljullu** [comment]
@timmyc I wouldn't say #957 is exactly the same issue as this one.

Actually, taking a second look at this issue, I think the fix is simpler than what I originally thought and should be implemented in the client, before we make the request. Currently, when we request the data for today we set the params to:
```
{
  after: 2017-12-27T00:00:00+00:00,
  before: 2017-12-27T23:59:59+00:00, // No matter what time of the day it is, we always request the data until 11:59PM
}
```
It would probably make sense to set the `before` param to the current time, that will make the API to return only the hours up to the current one.

That means no API changes are required. If this solution sounds good to you, I will create a PR with this solution tomorrow.

**Comment by timmyc** [comment]
Ah gotcha - yes that seems like a good solution too 👍
