### ISSUE TITLE
Dashboard: Add Click Action for Charts

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1191]
The charts displayed on the dashboard are meant to provide a quick view into key stats for a store, but also a launching point to dive deeper into a set of data.

![image](https://user-images.githubusercontent.com/22080/50456364-a68a9880-0908-11e9-946f-56f22e1d082a.png)

The goal with this enhancement is for the entire chart block to be a click target to take the user to the associated report/summary chart. So in the above screenshot clicking anywhere within the Items Sold block would take the user to the Products Report ( `/wp-admin/admin.php?page=wc-admin#/analytics/products` with default summary number / chart shown ) for the current dashboard date range - while clicking on Average Order Value would take the user to `/wp-admin/admin.php?page=wc-admin#/analytics/orders?chart=avg_order_value` with the date range added too.

__Questions__
- I'm not sure how to best handled this from an a11y standpoint ( @ryelle any ideas or input here? )?
- @LevinMedia I think we also discussed the need for a little bit of design input here. Perhaps a hover state on the chart blocks? Also does this really work well with the existing hover states for the tooltips when hovering on a data point in the chart? One alternate idea is to just make the chart block titles linked to the corresponding report which is the pattern used on the similar linking of dashboard tiles to deeper reports in WPCOM site stats:

![stats trout bummin wordpress com 2018-12-26 12-24-24](https://user-images.githubusercontent.com/22080/50456430-434d3600-0909-11e9-862f-c16ec412e826.png)

**Comment by LevinMedia** [comment]
@timmyc my original intent was for the entire block to be hoverable / clickable - It's noted with additional detail at p6riRB-3qG-p2 in the graph block section.

I think it would okay with the hover effects (tool tips etc) on desktop. They wouldn't be possible on mobile, so it's more of a bonus for desktop users. If it's a technical / accessibility hurdle, I'd be fine disabling all of the hover tooltips / interactions, and simply make the block click through to the associated report. The intent is at a glance info that drives deeper into the experience.

**Comment by ryelle** [comment]
Just to make sure I understand, I grabbed one of your mockups, and here's how I interpreted it. The red box is a clickable space that will take the user to that report page. The blue boxes are hover-only, and will highlight the corresponding line in the chart, clicking them will still take you to the report page. The dots on the line graph will trigger the hover card, but I think if you move the mouse into the hover card, it will "un hover" the graph block due to technical reasons, so it might be better to not have those.

![hoverable-graph](https://user-images.githubusercontent.com/541093/50649579-48833400-0f4c-11e9-909e-1ee54f2eb1ed.png)

Accessibility-wise, I think the hover/click wrapper will be mouse/tap-only (using onClick on the div, ignoring the jsx-a11y issue that comes up), and we'll have an alternative for keyboard/screen reader users in the form of a hidden but focusable link to the report page. Screen readers will read through and hear the link, then hear the graph like all the other graphs. Sighted keyboard users will tab through the page, and when they land on the link, it will appear above the graph, then they can move to the next block (because none of the graph will be interactive/tab-able content - unless we want to give focus to the blue boxes too, but if they don't have an action, is that useful?)

I do think we should have some indication when hovered that clicking will take the user to a new page, since it's a different interaction than expected from other graphs in wc-admin.

![hoverable-graph-annotated](https://user-images.githubusercontent.com/541093/50649967-35249880-0f4d-11e9-9338-2a8e29d51f8f.png)

Example of a focusable hidden link are the skip links in the twenty* themes, for example load https://ryelle.codes/ & hit tab, immediately you'll see a Skip to Content link.

<img width="395" alt="screen shot 2019-01-03 at 11 54 35 am" src="https://user-images.githubusercontent.com/541093/50650419-605bb780-0f4e-11e9-83bb-1826617015e3.png">

**Comment by LevinMedia** [comment]
>The red box is a clickable space that will take the user to that report page. The blue boxes are hover-only, and will highlight the corresponding line in the chart, clicking them will still take you to the report page. The dots on the line graph will trigger the hover card, but I think if you move the mouse into the hover card, it will "un hover" the graph block due to technical reasons, so it might be better to not have those.

You got it :D I'm going to move the conversation over to #1236
