### ISSUE TITLE
Add single category filter to categories report

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/wc-admin#1277]
See #1276.

A `single_category` filter should be added to the categories report, to allow viewing the graph/chart by a single category. This way the top selling categories block can link to that instead of a "compare" filter on a single category.

For prior art, a products equivalent of this already exists.

**Comment by justinshreve** [comment]
@timmyc I did some issue searching before opening this and didn't see anything but I just noticed this card https://github.com/orgs/woocommerce/projects/2#card-15975036. Seems like this all ties together, but will take some updates across reports to get working -- so maybe we should update this issue to cover and better track whats mentioned in that note?

**Comment by timmyc** [comment]
Yep David brought that up during his sweep, and I ended up converting the sweep issue to just cover that one item since that is all that was discovered on the tabular component #1102 - so definitely all related. In 1102 I suggested to start with the products report, but all of the reports with table text filters ( coupons, taxes, products and categories ) are going to need the single filter feature too.

I didn't go so far as to see if all the related endpoints support it though 🤞
