### ISSUE TITLE
Disable analytics and dashboard for users below WP 5.0

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/wc-admin#1355]
WooCommerce 3.6 **will not** have a hard version requirement of WordPress 5.0, however we need to disable analytics and dashboard for stores that can't support it. The rest of their store admin experience should be available. 

@josemarques what kind of notice do we want to display to prompt them to upgrade?

See p6q8Tx-PA-p2 #comment-2818 and p6q6po-9VP-p2 #comment-89107.

> if WP < 5.0 we don’t show the dashboard or reports, and don’t load the blocks JS as well.

> along with a notice/nudge for upgrading.

> Dashboard and analytics are not required for the rest of WooCommerce to function, so we should just disable them and allow the rest of the store to function.

**Comment by josemarques** [comment]
I'm assuming the links to the Dashboard and Analytics pages will still be visible even if the features can't be accessed? If that's the case I think we should display a regular warning notice nudging to upgrade to WordPress 5.0 only on those pages. @LevinMedia

**Comment by LevinMedia** [comment]
@justinshreve this issue has changed somewhat because we're going the featured plugin route for wc-admin and 3.6 - which means we can state in the plugin requirements that it requires 5.0 or greater - and I think that if the user still downloads and activates the plugin, and the requirements aren't met, we can use the same notification we're using now. That way they don't have to change the way the menus are implemented.
