### ISSUE TITLE
Chart 'type' parameter conflicts with the stock API endpoint 'type' parameter

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#1450]
- Go to the _Products_ report.
- Switch to the bar chart and verify `?type=bar` is appended to the URL.
- Go to the _Stock_ report.

An error appears:

`type is not one of all, lowstock, instock, outofstock, onbackorder.`

**Comment by timmyc** [comment]
Thinking a good fix here might to just update the [REST endpoint arg](https://github.com/woocommerce/wc-admin/blob/master/includes/api/class-wc-admin-rest-reports-stock-controller.php#L410) to something else, perhaps `status` since that makes contextual sense here - show products with the status of: lowstock, instock etc.

@rrennick let me know if this one looks like one you might want to take

**Comment by rrennick** [comment]
> we could rename the chart to `chartType` which would ensure no conflicts at all

That sounds good. This would be a good one for me to have a look at how the front end interacts with the api.

**Comment by justinshreve** [comment]
> This would be a good one for me to have a look at how the front end interacts with the api.

@rrennick I went ahead and assigned to you since I haven't started on this one and I'm looking at a separate stock issue at the moment (https://github.com/woocommerce/wc-admin/issues/1527).
