### ISSUE TITLE
Popover: Update Mobile Styling

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#151]
**Designs**: [inVision Project](https://automattic.invisionapp.com/d/main#/projects/prototypes/14659724)

When interacting with an Ellipsis menu in a small viewport, the experience currently looks like:

![image](https://user-images.githubusercontent.com/22080/42244621-9b6421ec-7eca-11e8-9f44-4c86f23c706e.png)

the hi-fi designs are seeking for the popover menu to look more like the following when on a small viewport:

![image](https://user-images.githubusercontent.com/22080/42245894-6c7b27b8-7ecf-11e8-8eaa-48d9009189e3.png)

**Comment by justinshreve** [comment]
I wanted to note that Gutenberg already has a prop for mobile pop overs. They are just disabled by default. If you enable them, they currently look like this:

<img width="538" alt="screen shot 2018-07-24 at 11 44 43 am" src="https://user-images.githubusercontent.com/689165/43150118-2264aaf0-8f37-11e8-9112-94f74799d15d.png">

( 2 text menu items, and 2 with icons)

--

Should we stick with the Gutenberg pattern for now, instead of implementing our own different behavior? cc @woocommerce/woo-core-design @timmyc

**Comment by timmyc** [comment]
➕ for sticking with the design pattern that is already in place, but @jameskoster might have more thoughts.

**Comment by jameskoster** [comment]
I didn't realise GB had a pattern for this. Agreed, let's use that.
