### ISSUE TITLE
Product ( Single ) Report Duplicate API Request

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1512]
**Describe the bug**
When viewing a Single Product Report, there are two API requests for the identical resource ( `/wc/v4/products`, the only difference being a `per_page` parameter which I don't believe is a valid query arg for this resource when requesting a single object. Wondering if we might be able to track down the code issuing the `per_page` request and remove that parameter so the data layer won't fire off two requests to the same resource. 

**To Reproduce**

1. Go to Products report
2. Add a filter for a single product
3. Probably easiest to do a hard refresh and see the requests once the query args are setup

**Expected behavior**
Don't perform duplicate API requests.

**Screenshots**
![duplicate-requests-products-page](https://user-images.githubusercontent.com/22080/52513734-90d3e880-2bc1-11e9-8f41-3229bd76cc5a.png)

**Comment by joshuatf** [comment]
That first call is used to grab the label for the Single Product Filter.  The call is initiated from [here](https://github.com/woocommerce/wc-admin/blob/ca5135b7a27afbe637fda1d8dff8d9af18ffc251/packages/components/src/filters/filter/index.js#L50).

The second is made from the actual report [here](https://github.com/woocommerce/wc-admin/blob/ca5135b7a27afbe637fda1d8dff8d9af18ffc251/client/analytics/report/products/index.js#L138) when `getItems()` is called.

Ideally, we can figure out a way to use `getItems()` to also populate the labels so we can avoid 2 calls here.

**Comment by psealock** [comment]
The decision was made a while ago to keep queries that populate labels in component state instead of the store. This worked well until a use of `getItems` was introduced to in the Product Report's `connect` function to determine if a product was variable or not:

https://github.com/woocommerce/wc-admin/blob/3ab71c08fd92a1915214be09afb57356aad0a6c4/client/analytics/report/products/index.js#L138-L140

Making changes to remove this duplicate call would involve changing all the filters to use the `getItems` method in a `connect` function instead of @timmyc's favourite line of code:

```js
getLabels( query[ filterParam ], query ).then( this.updateSelectedTag );
```

This is probably a good idea. However, at this stage I don't think the work involved in a refactor outweighs the detriment of an additional call. 

Unless there is another way I'm not seeing, I propose moving this issue to the backlog.

**Comment by joshuatf** [comment]
I tinkered around with this a bit and I think @psealock is probably right about the time involved here.

I'm not sure we can even directly replace the above line with a connect as this is part of `packages` and we won't want to connect it directly.
```js
getLabels( query[ filterParam ], query ).then( this.updateSelectedTag );
```

**Comment by justinshreve** [comment]
cc @timmyc -- thoughts on this?

FWIW, I played around with this as well and I can't think of a good solution going the other direction either. The extra request should only occur when a single product filter is selected, so not all product reports. One of the requests will also not repeat so it should only be the initial load as well.

I'd agree about punting for more exploration/a refactor later.

**Comment by timmyc** [comment]
Thanks for checking it out all, fine with punting this one.
