### ISSUE TITLE
Chart: Error: <rect> attribute width: A negative value is not valid. ("-817")

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#391]
Somehow I've gotten to a state with the numbers on my site where the following errors are shown and the chart:

![image](https://user-images.githubusercontent.com/22080/45397642-e0ec5600-b5f5-11e8-89f0-7f22aef38d09.png)

**Comment by greenafrican** [comment]
@timmyc which branch is this on? How can I replicate it? I can definitely start with the y-axis `pound` issue but I'm not sure what the data looks like or which `dateParser` prop you are using for this.

**Comment by greenafrican** [comment]
It seems this may be on `master`. As mentioned last night on the call, the reason this is happening is because the incorrect `dateParser` and date formats are being passed as props. In this example, The date format in the `chartData` array is `%Y-%m-%dT%H:%M:%S`:

![screenshot 2018-09-12 09 08 12](https://user-images.githubusercontent.com/1160732/45408178-e4babf80-b66b-11e8-9e8e-107891dc4d06.png)

And the `dateParser` is `%Y-%m-%d`:
![screenshot 2018-09-12 09 13 29](https://user-images.githubusercontent.com/1160732/45408288-395e3a80-b66c-11e8-9e19-bcc34f6ccc74.png)
