### ISSUE TITLE
Update Tag to Gutenberg Field Token

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#423]
Both the Advanced filters, and comparison filters should be updated to use the existing Gutenberg field token.

In the case of the comparison filter, the field token is located outside of the field (Directly below)
 
<img width="1252" alt="screen shot 2018-09-17 at 11 38 01 am" src="https://user-images.githubusercontent.com/4500952/45642795-297c9700-ba6e-11e8-9f5c-78e66b9839a6.png">

In the case of the advanced filters, the field token should reside inside the search field. 

<img width="658" alt="screen shot 2018-09-17 at 11 37 44 am" src="https://user-images.githubusercontent.com/4500952/45642802-31d4d200-ba6e-11e8-9eae-d4e20ab1664c.png">

CC: @ryelle @psealock

**Comment by joshuatf** [comment]
I'm working on a PR for this, but it looks like the Gutenberg token fields are purely text, whereas the current ones allow us to add our own label so we can include a product image.  Here are a few options:

* Use Gutenberg tokens and lose images in the autocomplete/suggestions field
* Try to get a PR in Gutenberg to allow labels for suggestions
* Keep current system

Thoughts?

**Comment by Aljullu** [comment]
Hey @joshuatf if I'm not wrong this issue was only referring to update the styles of the `<Tag>` component to look similar to Gutenberg's tokens, and I think that was fixed by #503 (my bad I forgot to close this issue and didn't see your message until today :worried: ).

Am I right @LevinMedia? Or is there something left to do regarding this issue?

**Comment by joshuatf** [comment]
@Aljullu I think you're right.  I spoke with @LevinMedia afterward and he seemed to think the same, but I'll wait for him to confirm here.

**Comment by LevinMedia** [comment]
@joshuatf @Aljullu On the front end, this looks good to me, so unless there's some other stuff ya'll need to update behind the scenes, the design looks good on master.

**Comment by joshuatf** [comment]
It would be great to reuse Gutenberg tokens so we're maintaining one less component in wc-admin, but this may not be a top priority at the moment and would require getting a PR through Gutenberg.

I'll close this issue for now since it seems this is mostly in reference to the aesthetics and things are looking good there.
