### ISSUE TITLE
Merging to WC Core: Use WC_Install approach for table updates, etc.

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-admin#532]
Core WooCommerce has a dedicated class for table updates (e.g. during activation/install). We should probably use it before/when wc-admin is merged to WooCommerce core.

See https://github.com/woocommerce/woocommerce/blob/14aea98d49b5afaa1b5f08c0cc1a1695392b089e/includes/class-wc-install.php

FWIW: Our existing approach (plugin activation hooks) is awesome for single sites, but not so great for network installs. See https://core.trac.wordpress.org/ticket/14170#comment:68 . Not sure if network installs are a requirement.

**Comment by justinshreve** [comment]
Right now, it seems like in most instances, you are required to go to Systems > Status Tools > Rebuild Reports to get analytics and the dashboard working. I was going to open a new issue, but this one seems related (and #430).

It looks like there is some code that is supposed to handle this automatically https://github.com/woocommerce/wc-admin/blob/f31f3354e15a1966093258e20de5e935438ab296/wc-admin.php#L100, but it doesn't seem like it always works for users (#1471, #1441).

It also doesn't seem to handle plugin upgrades -- I've definitely had to rebuild quite a few times.

@timmyc Flagging this as it seems like a blocker for the feature plugin -- so we should probably look in Sprint 13. Otherwise all our documentation and updates will require manually rebuilding steps.
