### ISSUE TITLE
REST API: Add New/Returning Customer to Order Stats Endpoint

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#558]
Follow-up issue of #418

As @Aljullu pointed out in the original issue:

> We are currently displaying the customer ID instead of the customer type (new/returning) because that's not implemented in the API yet.

So tagging @peterfabian and @claudiosanches on this one. Is it feasible to add this new customer field to the current API response, or are we going to have to pull data in from another endpoint.

**Comment by joshuatf** [comment]
This PR should resolve this https://github.com/woocommerce/wc-admin/pull/613 and add adds new/returning customer data count as an option in the data store.

Will close this issue pending approval of that PR.

**Comment by joshuatf** [comment]
This actually will not be resolved by #613 since the order information for the table comes directly from the order/meta information from the WP api and not from the order stats table.

@peterfabian has also left some greats comments for discussion on [when we should mark a user returning or new](https://protonpower.wordpress.com/2018/06/13/rest-api-v3-progress-mocking-episode-2/#comment-2684).

We should probably discuss that before doing any more work on this.

**Comment by joshuatf** [comment]
Update: the decision was made to track previous/returning customers based on previous order count and #613 does correctly track this.

However, the current stats do not reflect **number of returning customers** but instead track **number of orders by returning customers.**

In order to correctly determine these numbers, we would need to group by and add columns for `user_id` or `billing_email` (for guests) on the order stats table.  While this was the original plan, it looks like we're headed in the direction of adding a `wc_customers` table and we will be able to group by `customer_id` in that case (see p7bje6-1dM-p2).

If this is implemented, grouping by `customer_id` should resolve this issue and correctly reflect the stats.
