### ISSUE TITLE
Activity Panel: Inbox: Inbox Zero?

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-admin#615]
In the unlikely event that there are no entries to display in the Activity Panel Inbox, what should we display? This is what you see right now in such a situation:

<img width="819" alt="screen shot 2018-10-19 at 3 55 14 pm" src="https://user-images.githubusercontent.com/1595739/47247272-7c23d880-d3b7-11e8-94b8-ba813f815e1e.png">

Note: This is unlikely because 1) we don't delete items from the inbox, ever and 2) they will probably at least have the "customizer location has changed" entry in their inbox if nothing else. So this can probably be a low priority.

cc @LevinMedia

**Comment by josemarques** [comment]
Like mentioned that section will never be empty. In fact, there will be a few notices on day one. Here's a list of notices @warrendholmes  and I have been working on:

https://docs.google.com/spreadsheets/d/1iBcjWbQtN1DNZmvCmB4zmgGxiTL99_cJgeC2Ew2FvJE/edit?usp=sharing

Apart from those, there's also this list of promotions that will be pushed into that section:

https://docs.google.com/spreadsheets/d/1P5Ug8hwOQ-ig32MCct9C7LzNSTu8BpY_0awRJXvHtFc/edit?usp=sharing

So since there quite a few things to push there on day one this feels unnecessary. But I'm not against it. If it's something we can do easily go for it, it adds a nice touch.

**Comment by warrendholmes** [comment]
@allendav @LevinMedia @josemarques Do y'all have any ideas of how the Inbox would be empty? I can't think of how that could happen - which we should try guess before we decide what options we have.

**Comment by allendav** [comment]
There really is no reason for the inbox to be empty unless someone writes a plugin to empty it :)

**Comment by warrendholmes** [comment]
@allendav In that case, I don't think we should worry about this until we have better defined edge cases.

**Comment by timmyc** [comment]
Since this is an edge case / should never happen, i'm going to close this out.
