### ISSUE TITLE
Dashboard: Update Store Performance Design

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#661]
<del>Blocked by #660</del>

Designs: [inVision](https://automattic.invisionapp.com/d/main#/projects/prototypes/15060831)
Discussion: p6riRB-3qG-p2

__Current Design__
![image](https://user-images.githubusercontent.com/22080/47386623-f1e2b980-d6c1-11e8-9922-5746d7a8a5e8.png)

__Updated Design__
![image](https://user-images.githubusercontent.com/22080/47386643-fe671200-d6c1-11e8-9f73-85ea5839e967.png)

Once the new section header component is complete, this task involves updating the Store Performance section to use the new design as seen above.

**Comment by LevinMedia** [comment]
Available Performance Indicators:

*bold denotes default selections to include as they become available in the reports

**Gross Revenue > Revenue report - Gross revenue tab selected
Net Revenue > Revenue Report - Net Revenue tab selected
Orders > Order Report - Orders tab selected
Average Order Value > Order Report - AOV tab selected
Items Sold > Product Report - Items Sold tab selected
Refunds > Revenue Report - Refunds Tab selected**
Discounted Orders > Coupons Report - Discounted Orders tab selected
**Gross Discounted > Coupons Report - Gross Discounted tab selected**
Total Tax > Tax Report > Total Tax tab selected
Order Tax > Tax Report > Order Tax tab selected
Shipping Tax > Tax Report > Shipping Tax tab selected
**Shipping > Revenue Report - Shipping tab active**
Downloads > Download Report
Low Stock > Stock Report - Filtered by low stock products
Out of Stock > Stock Report - Filtered by out of stock products
**New customers > Orders report - Filtered by new customers
Returning customers > Orders Report  - filtered by returning customers**

**Comment by belcherj** [comment]
Couple of Questions and Thoughts:
-  Besides the header the design doesn't look any different to me.  Just looks like the numbers of blocks changes.  Is that correct?
- Each one of these blocks is hard coded in.  Seems like the wrong pattern
- Currently the toggles on and off are just saved in state.  On page refresh it will go back to default.  Is there a plan or api to save these settings?
- Since we will want to persist the layout of the dashboard would it not make sense to lay out this page programmatically from a json file?

@timmyc I think there is more work to do here than meets the eye.  Happy to add the additional blocks manually.

**Comment by ryelle** [comment]
> Each one of these blocks is hard coded in. Seems like the wrong pattern

In early discussions, we talked about having these defined in an API endpoint so that extensions could add extras via PHP filters – I think that got punted to a low-priority idea, but it's come up a few times since then so it might be worth bringing back up.

> Currently the toggles on and off are just saved in state. On page refresh it will go back to default. Is there a plan or api to save these settings?

There's [an issue to persist the table column settings](https://github.com/woocommerce/wc-admin/issues/272) on reports in user meta, we could use the same approach here.

> Since we will want to persist the layout of the dashboard would it not make sense to lay out this page programmatically from a json file?

That's an interesting idea, though for WP we should probably use a JSON object saved into user meta than creating files.

**Comment by belcherj** [comment]
> That's an interesting idea, though for WP we should probably use a JSON object saved into user meta than creating files.

Sorry, that's what I meant. Not sure why I used the term `file`.  I meant save off the JSON somewhere and then retrieve it later via the api. Exactly what you said!
