### ISSUE TITLE
Refund data not populating in revenue report

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#739]
**Describe the bug**
When a refund has been issued in your selected date range, the data is not appearing in the revenue report.

**To Reproduce**

Start by refunding an order that occurred within the last week. (When I attempted to refund an order, after clicking the refund button, I got stuck on the preloaded indefinitely. Eventually I refreshed the page, and it noted the order refunded. @psealock noted the same behavior) 

1. Visit the legacy reports, and note the refund data showing up there
2. Navigate to the revenue report, and ensure your date range includes the last week.
3. Note the refunded revenue is not appearing in the summary number, or in the tabular data on the date of the refund.

**Expected behavior**
Refund data should appear in both the summary numbers and tabular data

**Comment by joshuatf** [comment]
I also had the same issues with refunds needing to be refreshed. 
 Upon further digging it looks like this is because something in wc-admin (presumably our router) is blocking the `window.location` from working which the refund function relies on to reload this page -https://github.com/woocommerce/woocommerce/blob/696e22f013b08eb9334d2c806df9e206310b2fe2/assets/js/admin/meta-boxes-order.js#L753

@LevinMedia just to confirm the expected behavior here, should a refund appear on its own line so we can properly track its date?

<img width="1490" alt="screen shot 2018-11-01 at 6 36 25 pm" src="https://user-images.githubusercontent.com/10561050/47885884-362e3200-de05-11e8-97a0-1da594db8cc1.png">

Or do we just want to ignore the dates and reduce the original total by the refund amount?

**Comment by LevinMedia** [comment]
> Or do we just want to ignore the dates and reduce the original total by the refund amount?

^^ This ^^ - Because the order report is based on the dates the orders were placed, the order status would be updated to refunded, and we'd reduce the net revenue by the refunded amount.

**Comment by joshuatf** [comment]
The order page was not reloaded after processing the refund since the React Router appends a `#` to the URL and this won't work with `window.location.href` used by WC.  Opened a PR [here](https://github.com/woocommerce/woocommerce/pull/22116) to resolve this.

Will open a separate PR here to address the refunded amount in the report tables.
