### ISSUE TITLE
Add support for advanced filtering of orders

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/wc-admin#749]
Orders endpoint needs additional filters to support the frontend:

`match`: [any, all]
which affects the following additional filters:

- Order status
  - `status_is`
  - `status_is_not`
  - e.g.: `status_is=pending,complete`
- Product 
  - `product_includes`
  - `product_excludes`
  - e.g. `product_includes=123,456`
- Coupon codes
  - `coupon_includes`*
  - `coupon_excludes`*
  - e.g. `coupon_includes=309&coupon_excludes=245`*
- Customer
  - `customer`
  - e.g. `customer=new`

Already existing filters:

- `categories`
- `after`
- `before`
- `page`
- `per_page`
- `interval`
- `order`
- `orderby`

Of the existing ones, maybe categories should be also affected by the match all/any?

ref P2: 
https://protonpower.wordpress.com/2018/06/28/rest-api-v3-orders-report/#comment-2575

*Updated after comments below

**Comment by psealock** [comment]
>Of the existing ones, maybe categories should be also affected by the match all/any?

An advanced filter for categories is not in the initial designs, but I think you are right and it should be added now because it fits with other all/any terms and might prevent future confusion.

Also, just a couple things with coupons:

* There won't be `_is/_is_not`
* Can the prefix simply be `code`?
* Can we use ids only instead of actual codes?

eg

- Coupon codes
  - `code_includes`
  - `code_excludes`
  - e.g. `code_includes=245,309

**Comment by peterfabian** [comment]
@psealock ad the `coupon_code` vs `code`: I just thought it might be clearer, as it's not order code but coupon code, i.e. ` https://server/wp-json/wc/v3/reports/orders/stats?code_includes=245` sounds like the code relates to orders, but we can change it easily once this is implemented, after all.

**Comment by psealock** [comment]
Sounds good @peterfabian
