### ISSUE TITLE
PHP Unit tests are failing

### ISSUE THREAD

**Issue by belcherj** [woocommerce/wc-admin#848]
$ bash bin/phpunit.sh
PHPUnit 7.4.3 by Sebastian Bergmann and contributors.
PHP Fatal error:  Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test) in /tmp/wordpress-tests-lib/includes/phpunit6-compat.php on line 18
Fatal error: Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test) in /tmp/wordpress-tests-lib/includes/phpunit6-compat.php on line 18

https://travis-ci.org/woocommerce/wc-admin/builds/455053382?utm_source=github_status&utm_medium=notification

Thinking it might be related to:  https://github.com/woocommerce/wc-admin/pull/758

**Comment by belcherj** [comment]
Could be that the branches are out of date

**Comment by allendav** [comment]
it shouldn’t be running phpunit 7.4.3
should be 6.x
did composer install perhaps not happen?
or maybe that branch was out of date? this (incorrectly using 7 instead of 6) was very recently fixed (as in 9 hours ago) in https://github.com/woocommerce/wc-admin/pull/758/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R15 (edited)

**Comment by belcherj** [comment]
That fixed it.  The branch was out of date.
