### ISSUE TITLE
REST API: Create new /v4 of Orders Endpoint

### ISSUE THREAD

**Issue by psealock** [woocommerce/wc-admin#950]
Thus far, populating the orders table from the established `/orders` endpoint has been working great. Filtering by Advanced Filters in #943 will introduce query parameters which have no meaning in the context of the endpoint. 

We can keep using `/orders` by filtering client side. For example, an advanced filter of `?status_is_not=pending` can be turned into `?status=...` using `wcSettings.orderStatuses` to explicitly ask for all but pending orders.

`product_includes=65` can also be translated to the correct query argument (`product`), but only accepts a single value. We'll need to filter by multiple ids.

The limitations are clear with query argument `&customers=new`. We can get customer data via `/customer` and compare results with `customer_id` from the order, but that won't give an indication of new/returning.

Likewise, we can't filter by `coupon` in the `/orders` endpoint.

Seems to me like we'll need to write `/reports/orders`. Do you agree @peterfabian ?

**Comment by peterfabian** [comment]
I think you're right. Maybe we could add required filters to `/orders` endpoint? 

Because otherwise, `/reports/orders` would return the same data (or a subset of data from `orders`), and would just add support for extra filters, if I understand the problem correctly?

@claudiosanches what is your view on this? Do you have any preference regarding new endpoint/updating `/orders`?

**Comment by claudiosanches** [comment]
@claudiosanches I happy to introduce new endpoints for reports.
When possible, it's always great to introduce new filters into the current endpoints, still most of filters here probably more related to reports, so I don't see any problem having a new endpoint, also probably better that we don't need to list so many data at once too, since our reports displays less data and having the IDs it's possible to query the regular endpoint for more details.

It's nice that we are going back to our initial idea, where we introduce all fields required by our new reporting system, and doing less requests :smiley:

**Comment by timmyc** [comment]
Seems like if we want to fully support the advanced filter query args, we will likely need to version the `orders` endpoint to `/v4` - or as suggested above we can try to use [this filter](https://github.com/woocommerce/woocommerce/blob/master/includes/api/v2/class-wc-rest-orders-v2-controller.php#L418) to manipulate the requisite query args:

Advanced Filter Arg | /wc/v3 Argument |
--------------------|-------------------|
`status_is (string)`|`status (string)`
`status_is_not (string)`| NA
`product_includes (int|array)`|`product (int)`
`product_excludes (int|array)`| NA
`coupon_includes (int|array)`| NA
`coupon_excludes (int|array)`| NA
`customer (string)`|`customer (int)`

The most challenging of the above is `customer` due to the mis-match of data types - which we could either update the logic in the orders stats endpoint to accept an arg of `customer_type` perhaps - and match that in a new `/orders` endpoint or vice-versa.

Given the gaps of the required advanced filter args contrasted to the current options in the `/v3` endpoint - it seems like creating a new version 4 here in wc-admin is the best route forward. As such I've updated the issue title to reflect that need. I also think that these arg additions to the base orders route could be useful for other developers and all make sense as good additions to the core endpoint ( though would still love to hear thoughts on this from @mikejolley @peterfabian and @claudiulodro )

**Comment by claudiulodro** [comment]
I recommend using `v4` endpoints for **everything** in wc-admin for the following reasons:

- We can't add any of the new endpoints into the `v3` namespace.
- It doesn't make sense to mix and match endpoint namespaces in a feature. 
- It also wouldn't really make sense to have a `v4` namespace that doesn't contain all of the existing core `products`, `orders`, etc. endpoints.

Let me know if you have any questions or need clarification about anything.
