### ISSUE TITLE
Product report chart truncated or missing entirely

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#957]
**Describe the bug**

- The Product report truncates the chart when no data is present for the last part of a selected period. 
- If no data is available for the entire selected time period, the graph does not render. 

Current behavior when no data is present for the last part of a selected period:

<img width="1728" alt="screen shot 2018-11-28 at 11 28 52 am" src="https://user-images.githubusercontent.com/4500952/49177449-24f01c80-f302-11e8-9d3b-c49cb3a8e9a8.png">

Current behavior when no data is present for the entire selected period:

<img width="1737" alt="screen shot 2018-11-28 at 11 31 03 am" src="https://user-images.githubusercontent.com/4500952/49177146-51efff80-f301-11e8-9010-e5d78027813f.png">

**To Reproduce**

1. Go to your order management screen and delete at least the last week worth of orders
2. Visit the product report
3. Select any of the "to date" preset date ranges. Ensure it's longer than the time frame of orders you deleted in step one (ie: quarter to date)
4. Note the chart ends the last day there was data, not the last day of the selected date range.
5. Change the date range "Week to date"
6. Note the chart does not render

**Expected behavior**
The entire selected date range should always appear in the chart.  If there is no data for the selected date range, the line chart should flatline across the bottom. See screen shots from revenue report below. 

**Screenshots**

Expected behavior when no data is present for the last part of a selected period

<img width="1733" alt="screen shot 2018-11-28 at 11 34 46 am" src="https://user-images.githubusercontent.com/4500952/49177290-b4e19680-f301-11e8-85c8-c12c5d3e4734.png">

Expected behavior when no data is present for the entire selected period:

<img width="1728" alt="screen shot 2018-11-28 at 11 32 04 am" src="https://user-images.githubusercontent.com/4500952/49177145-51efff80-f301-11e8-8491-0a69ef698570.png">

**Desktop (please complete the following information):**

* OS: osx 10.13.6
* Browser Chrome 
* Version 70.0.3538.110

**Additional detail:**

If there is no data in the selected period, or comparison period, or if you're using a comparison chart and there is no data for any of the series being compared, the chart should always render the entire selected date range. Design will provide a mock for charts without data in a separate issue.

**Comment by greenafrican** [comment]
Great catch @LevinMedia 

I've had a look at this and it's not an issue with the chart components and the expected behaviour can be observed in the existing _Revenue_ report:

![screenshot 2018-11-29 10 59 42](https://user-images.githubusercontent.com/1160732/49210493-e1f77d00-f3c5-11e8-8507-6136744a053b.png)

And for the period without any `primaryData`:
![screenshot 2018-11-29 11 00 25](https://user-images.githubusercontent.com/1160732/49210546-08b5b380-f3c6-11e8-9701-0cc39543f94c.png)

It seems as though this is an issue with the `reports/products/stats` endpoint as it only returns data up until the date of the last order (for example 13th Sept in the above examples) in the series, rather than zero-fill the primary data set to the end of the `before` date (for example 21st Sept in the above example).

cc @timmyc

**Comment by timmyc** [comment]
Ah interesting - definitely does sound like a bug with zero fill in the API response. /cc @peterfabian
